version: "3"
services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token $TOKEN
    restart: unless-stopped
    network_mode: host